### ISSUE TITLE
Your Website is offline

### ISSUE THREAD

**Issue by piperpilot** [engineertype/ControLeo2#1]
Hi,

It seems your website is offline.  I was interested in purchasing a controleo2.

Thanks!

**Comment by engineertype** [comment]
Hi,

Sorry about that.  The server went down on Friday while I was on vacation.
I'm working with the hosting company to get it back up.  It should be back
later today.

If you tell me what you want, and where to ship it to I can send you a
PayPal invoice.

Regards,

Peter

**Comment by engineertype** [comment]
The web site is back up now.  http://whizoo.com.

Peter
