### ISSUE TITLE
Controller still resetting when operating servo with 220uF cap installed.

### ISSUE THREAD

**Issue by jcoffland** [engineertype/ControLeo2#10]
A few months back I bought reflow kit which came with a MG996R servo.  I also used the recommended oven.  Everything was working fine but the controller would often still reset with the supplied 220uF cap installed.  I double checked the capacitor polarity and connections and buzzed them out with my meter to make sure my soldering was good.  Adding an additional 1000uF cap across the screw terminals of the 5v input solved the problem.  I thought you should know.  This might also be helpful to others.

**Comment by engineertype** [comment]
Thanks for the feedback.  Extra capacitance helps, and adding the extra capacitor you did will improve things.
