### ISSUE TITLE
PID Request

### ISSUE THREAD

**Issue by gnalbandian** [engineertype/ControLeo2#11]
Hello.
Great Controller. I have made one for myself and after fine tuning it, it's  working great.
Have you thought in implementing PID algorithm to control heater element?

Is there any reason to avoid this?
Thanks.

**Comment by engineertype** [comment]
1. The element cycle times are not predictable with PID, leaving the element glowing red or off for long periods at a time.  This creates hot and cold spots. 
2. PID is on / off for all elements at the same time, but ControLeo2's software can manage cycles to have more heat from the bottom.
3. ControLeo2's software is better for managing current draw

**Comment by gnalbandian** [comment]
For number 2, we can have as many PID controllers in the same ControLeo as heating element we need to control (no need of PId for coolers or convection fans). Each output can be limited, for example, bottom heater ranges from 0% to 100% while top heater 0% to 50%. This is possible with the available arduino PID library.
We can also modify the PID setpoint temperature depending of the phasetime in order to achieve the most accurrate curve.
We can also sort some way of managing current draw effectively.

Let me know what you think.
