### ISSUE TITLE
ReflowWizard - how to change reflow profiles?

### ISSUE THREAD

**Issue by joymonkey** [engineertype/ControLeo2#13]
I feel like I must be missing something that's right in front of my face, so I apologize for the question I'm about to ask:

I'm going from using regular solder paste to some low temperature paste for a project with sensitive components. This is my new paste:
http://www.chipquik.com/datasheets/SMDLTLFP10.pdf
Where do I adjust the temperatures in the ReflowWizard sketch to match the solder paste that I'll be using? I can't seem to find the values in the sketch.

**Comment by engineertype** [comment]
Hi,

Please take a look at https://www.whizoo.com/profiles.  The default profiles are a good place to start, but should be tweaked to suit your oven and your paste.

Profiles are loaded using an SD card.  There are no software/firmware changes needed to modify profiles.

Peter

**Comment by joymonkey** [comment]
Thanks for the details, but that only seems relevant to the Controleo3. How are profiles adjusted on the Controleo2?

**Comment by engineertype** [comment]
My bad, sorry!  For ControLeo2 you have to change the "max temperature" setting then redo the learning cycles.

Peter
