### ISSUE TITLE
Free up a bunch of SRAM, easily ...

### ISSUE THREAD

**Issue by gruvin** [engineertype/ControLeo2#2]
Howdy.

You should use Flash memory for all `Serial.prints` that only send string constants. Like so ...

Replace ... 

```
Serial.print("Last profile loading from eeprom: ");
```

... with ... 

```
Serial.print(F("Last profile loading from eeprom: "));
```

... and similar for the `MoveToNextPhase(...)` function, like so ....

```
MoveToNextPhase(F("Max Duration Exceeded"), timeInPhase);
```

... and a slight change to the function declaration itself ...

```
void MoveToNextPhase(const __FlashStringHelper *reason, int timeInPhase)
{
  Serial.print("**");
  Serial.print(reason);
  ...
```

... then you will get back 500+ bytes of wasted SRAM, as well lose the Arduino IDE warning about SRAM resources being low and potential instability, yadee yada. 

Then, all that extra RAM could go towards neat new features you add with the 50%+ code space still remaining. Coffee warmer? :-P

I would have posted a pull request for the above, but I've made a whole bunch of other experimental changes and it's a bit of a mess right now. Anyway, hope it helps.

Having fun with my new oven! Thanks for the good works! :-)

Gruvin
Wellington, New Zealand

**Comment by gruvin** [comment]
P.S:  For what it's worth, that can all be done other ways, using `PROGMEM`, `PSTR`, `pgm_read_byte_near` and what not. But the documented Arduino way (which does all that stuff in the background) is much neater and cleverly integrated into the Serial class, to handle different argument types and all that good jazz.

I guess what I'm saying is that my changes are Arduino sanctioned / intended methodologies -- if there is such a thing. ;-)

**Comment by engineertype** [comment]
ReflowWizard does use the "F" macro to place strings into flash.  ReflowOven sketch is old, and no longer used.

**Comment by gruvin** [comment]
Far out. So I've been wasting my time trying to get this thing working?

So what should I be using and where do I find the documentation to tell me
that? Seems there's many versions floating around all over the place and
it's difficult to know what is what. Could you not delete the older stuff
or at least update the README's to indicate what is what? I like to help
out with open source projects but this not knowing where anything is at is
very frustrating.

Thanks.

Bryan.

**Comment by engineertype** [comment]
ControLeo2 ships with the ReflowWizard software installed.  The README (https://github.com/engineertype/ControLeo2) mentions ReflowWizard.  Also, if you look at the modification dates of the various files, only ReflowWizard has been updated since since the initial check-in.
Sorry for your frustration.  I don't believe in deleting older, some-what useful software but I'll keep your comments in mind for future releases.
Peter

**Comment by gruvin** [comment]
OK Peter. Good stuff. That does indeed help.

I think what happened is that last time I loaded a "Wizard" version of some
kind -- I think was part of the original ControlLeo? -- it was seemingly
only for testing and tuning PID parameters. So ,next time I saw
Reflow-"Wizard", I ignored it on that basis, especially because the code
comments in ControlLeo2 still talk about it being the latest greatest AND
that the PID stuff has been abandoned. So, it all kind of leads to a a bit
of a wild goose chase, you see.

I appreciate that the code is there to support your hardware product. But
you have made it open source and I did make certain assumptions around
that, based on the many other open source projects out there. If there's
ever anything I can do to help with any of this, please let me know.

gruvin [blah-at] gmail.com, should you wish to contact me outside the issue
tracker. No hard feelings if you don't of course. ;-)

Thanks for your time and of course, your continued efforts with this most
useful project!

Bryan.
