### ISSUE TITLE
Flux charring 

### ISSUE THREAD

**Issue by electrophile** [engineertype/ControLeo2#4]
Hi, I built my own hardware for the Controleo2 using [Brian Barrett's design](http://brianmakesit.com/reflow-oven-controller-controlleo-2-compatible/?v=5995289c850f). My boards do get soldered well, except that the solder melts at about 180-183 deg C (I'm using [this solder paste](http://www.chipquik.com/store/product_info.php?products_id=410002)) and in the final boards the flux is charred and the board silkscreen is all yellow. Any idea why this is happening? The reflow profile after exiting the learning mode is attached here.

[reflow profile (XLS and CSV).zip](https://github.com/engineertype/ControLeo2/files/211766/reflow.profile.XLS.and.CSV.zip)

**Comment by engineertype** [comment]
Hi, Glad to hear you like ControLeo2.  I offer my customers unlimited free support; part of every sale goes towards paying for this as well as continued software development.  I cannot offer non-customers free support.  I'm happy to have open-sourced my software and build guide and I'm glad that non-paying customers have found it useful.  If you would like to make a donation to support this effort, you may do so here: https://paypal.me/Whizoo.
Regards,
Peter
