### ISSUE TITLE
Door not closing after bake cycle cools below 50C

### ISSUE THREAD

**Issue by jcwren** [engineertype/ControLeo2#7]
Sooo... Firmware 1.7, 55C bake cycle for 5 minutes. Door now opens, but never closes.

**Comment by jcwren** [comment]
Also, unlike a reflow cycle, an abort does not close the door.

**Comment by engineertype** [comment]
Ah, serves me right for including someone else's code! I'll see about fixing this soon.

**Comment by jcwren** [comment]
If you're in a mood to re-write it, it would be nice if had the same level of temperature control that the reflow cycle does. Setting for 55C often gives me an overshoot to 65 or even 68C. And it takes a while to come down since the oven is fairly well insulated.

**Comment by engineertype** [comment]
I'm closing this now.  Version 1.9 fixes all the issues. :-)
