### ISSUE TITLE
Recommended oven: Oster TSSTTVF816

### ISSUE THREAD

**Issue by romanchyla** [engineertype/ControLeo2#8]
Hi,

I've bought the ControlLeo2 (but don't know your email), so I chose to use github. I spent quite some energy trying to find the best convection oven; ie. quartz elements, small (but not tiny), with fan, well built

I'd recommend you add it to the list of recommended ovens: Oster TSSTTVF816

Its internal construction is solid and it was relatively easy to fit 4 SSRs. With the boost element it has 1650W, but the first two learning runs ended because of the "too fast" soak, I think it would work perfectly without the boost element.

I'm attaching a chart of my testing run and few pics from the build.

![image](https://cloud.githubusercontent.com/assets/411794/19622412/0e859138-9877-11e6-903d-18a172fce611.png)

https://www.dropbox.com/sh/k70w67po2kize26/AAAVaG-BAQXSAaKS52i60Kjma?dl=0

**Comment by engineertype** [comment]
Thanks for the feedback.  The preferred way to reach us is through our web site:
http://whizoo.com/about

It is always better to have more heating elements than too few.  This means the elements can run cooler which helps to eliminate hot spots.

Regards,

Peter
