### ISSUE TITLE
incorrect led is bind to output D6

### ISSUE THREAD

**Issue by sylphio** [engineertype/ControLeo2#9]
hi,  when testing manually  or reflowing. when my boost element start (on D6) the second led light is set and not the third one. normal or not?

thank
seb

 it use

**Comment by engineertype** [comment]
Hi,

The best place to ask for support is our web site:
http://whizoo.coom/about

All ControLeo2's are tested before they are shipped.  D4 is the first LED, D5 is the second LED, D6 is the 3rd LED and D7 is the 4th LED.  If they are not lighting up this way you should check your wiring.

Regards,

Peter
